### ISSUE TITLE
Debugger for Unity 2.7.3 and C# 1.21.14 causing issues.

### ISSUE THREAD

**Issue by torano111** [Unity-Technologies/vscode-unity-debug#162]
## Expected Behavior
Intellisense should work correctly.

## Current Behavior
No Intellisense, and the VS Code freezes on save.

## Possible Solution
Install Debegger for Unity 2.7.2 then manually install C# 1.21.12.

## Steps to Reproduce (for bugs)
Get C# 1.21.14 and Debugger for Unity 2.7.3 from VS Code.

## Context
Previously(I think before 2.7.3), manually installing C# 1.21.12 fixed the issue. I think changing Marketplace publisher for the C# extension from ms-vscode to ms-dotnettools in C# 1.21.13 caused the issue, and so going backward fixed it. But with 2.7.3 this doesn't solve the issue. If you do that, you get 2 C# extensions(ms-vscode and ms-dotnettools), and you cannot uninstall/downgrade the latest version of C# because Debugger for Unity 2.7.3 depends on it. So you have to downgrade the Unity extension first.

## Environment
* Unity Version: 2019.3.0f6
* VS Code Version: 1.43.0
* C# Extension Version: 1.21.14
* Version of the debugger tool: 2.7.3
* Operating System and version: Windows

**Comment by marknash666** [comment]
The same problem，it just don't work well any cases

**Comment by ThomasZJ** [comment]
The same problem, and command "Unity Attach Debug"  doesn't work

**Comment by miniwolf** [comment]
> But with 2.7.3 this doesn't solve the issue. If you do that, you get 2 C# extensions(ms-vscode and ms-dotnettools), and you cannot uninstall/downgrade the latest version of C# because Debugger for Unity 2.7.3 depends on it. So you have to downgrade the Unity extension first.

Is this a work around for the problem? Uninstalling both the debugger extension and vscode extension and reinstalling latest?

**Comment by miniwolf** [comment]
@ThomasZJ the unity attach debug, could you report a separate issue for that, I would like to work on that separately.

**Comment by MarnixArnold** [comment]
Seeing the same problem with Debugger **2.7.4**, ms-vscode 1.21.14 and Unity 2017.4.36f1:
- No Intellisense
- Unity Editor freezes when trying to run with VS Code debug running.

**Comment by Romeno** [comment]
Downgrading to Debugger to 2.7.2 and ms-vscode 1.21.12 solved this temporarily.

**Comment by Neves97** [comment]
Same problem,

> Seeing the same problem with Debugger **2.7.4**, ms-vscode 1.21.14 and Unity 2017.4.36f1:
> 
> * Unity Editor freezes when trying to run with VS Code debug running.
Same problem, and it seems to not be possible to pause the debbuger when this happens

**Comment by f0ff886f** [comment]
Maybe not an option for all but I switched back to VS2019 Community. Impossible to work when your IDE is broken by 3rd parties, for now VS2019 is quite stable.

**Comment by fyk-1** [comment]
Tried different versions of vscode-unity-debug and ms-vscode with no avail in VS Code 1.43.
In the end reverting to VS Code 1.42.1 did it for me (with ms-vscode 1.21.12 and unity-debug 3.0.1).
Hope it can help!

**Comment by RobStorm** [comment]
> Tried different versions of vscode-unity-debug and ms-vscode with no avail in VS Code 1.43.
> In the end reverting to VS Code 1.42.1 did it for me (with ms-vscode 1.21.12 and unity-debug 3.0.1).
> Hope it can help!

I don't see that unity-debug version? Or am I thinking of something else...

**Comment by ThomasZJ** [comment]
> @ThomasZJ the unity attach debug, could you report a separate issue for that, I would like to work on that separately.

I guess that's same issues

**Comment by dftty** [comment]
https://github.com/Unity-Technologies/vscode-unity-debug/releases
Here is unity-debug 3.0.1, you should download and install it by manually.

**Comment by accidentalrebel** [comment]
I have C# 1.21.14 and Debugger For Unity 3.0.1 and I still have the same problems. Sometimes it works, sometimes it just crashes.

What should I do to debug this? Like error logs?

**Comment by miniwolf** [comment]
Freezes may mean that the debugger is stuck in some evaluation, or that it has "forgot" to send a resume call to the mono vm. Everytime you do a step or similar the mono vm needs a resume to continue. If that is not getting send then the mono vm hangs.
To figure that out it requires building a mono vm, from here: https://github.com/Unity-Technologies/mono
Then using the source of this repo and debug both to figure out what is going on.

**Comment by stephan1994w** [comment]
Has anyone been able to get their debugging back? I've reverted both and I get intellisense back, but debugging refuses to work and just hands. Even with the upgrade to 2.7.5

**Comment by Thaina** [comment]
`C# 1.21.14` has an issue, it seem not related to unity debugger

https://github.com/OmniSharp/omnisharp-vscode/issues/3668

We just need to revert C# back to `12.21.12` and also revert unity debugger extension to the last year's version. The process is annoying though, we need to install C# version `12.21.12` by downloading `vsix` manually, then revert unity version, then uninstall C# `12.21.14`

**Comment by stephan1994w** [comment]
> `C# 1.21.14` has an issue, it seem not related to unity debugger
> 
> [OmniSharp/omnisharp-vscode#3668](https://github.com/OmniSharp/omnisharp-vscode/issues/3668)
> 
> We just need to revert C# back to `12.21.12` and also revert unity debugger extension to the last year's version. The process is annoying though, we need to install C# version `12.21.12` by downloading `vsix` manually, then revert unity version, then uninstall C# `12.21.14`

Are you able to debug now you've reverted? I reverted and regained omnisharp functionality, but attaching the debugger freezes Unity

**Comment by Thaina** [comment]
@stephan1994w Yes I could

**Comment by Louqou** [comment]
I've found a solution that works for me (make sure extension auto-update is disabled in vscode settings)

1. Uninstall debugger for unity and C#
2. Restart Vscode
3.  Download C# 1.21.12 from here https://github.com/OmniSharp/omnisharp-vscode/releases
4. In Vscode install the vsix manually (ctrl+shift+p and search vsix)
5. Restart Vscode and wait for the .Net stuff to install (progress in Output log at the bottom)
6. Intellisense should now be working
7. Download unity debugger 2.7.2 from here https://github.com/Unity-Technologies/vscode-unity-debug/releases
8. Install it manually and restart vscode.

Both intellisense and debugger should now be working!

**Comment by filipw** [comment]
this is resolved in prerelease [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15).

**Comment by accidentalrebel** [comment]
> this is resolved in prerelease [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15).

It works now. 
- C# 1.21.15
- Debugger for Unity 2.7.5.

**Comment by ghiboz** [comment]
I have all the latest updates, but the debug still freeze unity editor

**Comment by torano111** [comment]
C# 1.21.15 and Debugger for Unity 2.7.5. fixed the issue for me. Don't forget to remove ms-vscode C# if you tried the manually-downgrade-solution.

**Comment by okanyildiran** [comment]
I have C# 1.21.15 and Debugger for Unity 2.7.5 but still unity editor freeze when it hits the breakpoint. 

Using Unity 2018.4.10f1.

**Comment by ghiboz** [comment]
> I have C# 1.21.15 and Debugger for Unity 2.7.5 but still unity editor freeze when it hits the breakpoint.
> 
> Using Unity 2018.4.10f1.

yes, same here with Unity 2018.4.18.f1

**Comment by maggiechen** [comment]
Same here with 2018.4.15f1, I uninstalled the C# extension and restarted VSCode before trying to install the vsix. It gets to the breakpoint but doesn't let me enter local variables or highlight the line that the breakpoint is on. The Step Into/Over/Out functions are greyed out despite Thread 1 saying that it's `PAUSED ON BREAKPOINT`

**Comment by wanakubwa** [comment]
For unity 2019.2.4f1 solution from @Louqou works fine (thanks!) but you need to downgrade VS Code version to 1.42.1 (https://code.visualstudio.com/updates/v1_42) and disable auto-update also for VS Code.

**Comment by maggiechen** [comment]
oh god thank you so much that worked. I was going nuts having to use visual studio community to do debugging

**Comment by miniwolf** [comment]
Can people here confirm whether downgrading VSCode to 1.42.1 solves the problem? If that is the case, we need to be in contact with the people on https://github.com/microsoft/vscode to resolve this issue

**Comment by cs-altshift** [comment]
@miniwolf I can confirm that downgrading to VSCode 1.42.1, C# extension version 1.21.12 and Unity Debugger 2.7.2 works. However, I have many problems with the C# extension sometimes not recognizing my solution.

**Comment by miniwolf** [comment]
He suggests that the issue may have been solved in the newest Insider version of VSCode. Can anyone confirm that? https://code.visualstudio.com/insiders/

**Comment by cs-altshift** [comment]
The debugger in version 2.7.5 works with the insiders version. Tested right now.

**Comment by miniwolf** [comment]
@cs-altshift thank you for testing :)

**Comment by wanakubwa** [comment]
@miniwolf For VSCode ( https://code.visualstudio.com/insiders/ ), Unity Debugger - 2.7.5 and C# extension - 1.21.16 debugger works as expected without previous problems.

**Comment by miniwolf** [comment]
Closing this as VSCode 1.44 has been released
