### ISSUE TITLE
Debugger Hang on step in Read Or Write property

### ISSUE THREAD

**Issue by fjqingyou** [Unity-Technologies/vscode-unity-debug#80]
Hello!

i'm Sorry, My English very bad , please forgive! thanks!

VSCode Version 1.22.2 (1.22.2)
Debugger for unity version : 1.3.0
OS: Mac os Sierra , version 10.12.6

using UnityEngine;

/// <summary>
/// This a debugger hang reproduce Test Class
/// </summary>
public class Test : MonoBehaviour{

#region  Test Mode 1
    private int m_TestProperty;

    //block to read or write for debug mode step in
    public int testProperty{
        get{
            return m_TestProperty;
        }
        private set{
            m_TestProperty = value;
        }
    }
#endregion

#region  Test Mode 2
    private int testProperty2{get; set;}
#endregion

    public int testProperty3{get; set;}

    protected void Start(){
        /*
        this test Mode 1
        set this code line break point, and debug startup
        where debugger break on this, press F11 step in, debugger hang reproduce
         */
        testProperty = 1;//Block
        Debug.Log("step in not execute to this for test mode 1");

        //this Test mode 2
        testProperty2 = 1;//if commented code testProperty = 1，on this code line step in , Debugger Hang too
        Debug.Log("step in not execute to this for test mode 2");

        testProperty3 = 1;//this not set break point，this simulation other Environmental init
        TestMode3(testProperty3);//break point on this code line, step in, Debugger Hang too
    }

    /// <summary>
    /// test step in Debugger Hang too
    /// </summary>
    /// <param name="testParame"></param>
    protected void TestMode3(int testParame){
        Debug.Log("step in not execute to this for test mode 3");
    }
}

**Comment by miniwolf** [comment]
These problems should be solved by upgrading to the preview release. @fjqingyou you can find the build here: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
I hope this solves your problem?

**Comment by fjqingyou** [comment]
@miniwolf 
Thanks!

i not mac os now,  my home only a window system win7, on win7 platform current bug still exist. 

mac os platform need 05-02 go to work test.

**Comment by fjqingyou** [comment]
@miniwolf 

Yes, Debugger for Unity version 2.4.2 

i'm at home now,

My Home PC Win7  X64 Service pack 1, VSCode Version 1.18.1, Unity Version 5.6.3f1

oh 05-02 is Date 2018-05-02, China date.

Today and tomorrow Holiday and vacations

**Comment by miniwolf** [comment]
This seems to be a problem specific in the legacy runtime system inside of Unity. It happens both on 5.6.3f1 as you say, but also on the newest possible version when using the legacy runtime system .NET 3.5. However in the new stable NET 4.x system in Unity 2018.1 this is working.

**Comment by fjqingyou** [comment]
@miniwolf 

but, VS2015 not exists this bug?  why?

**Comment by miniwolf** [comment]
Hmm.. That is kind of a good question. I know that I don't have the answer, but I can give you my thoughts on this. The problem is not something that can be solved by modifying my own code. This problem probably lies within the debugger-libs that I am using. Studio is relying on their own implementation to talk to the mono runtime. Which is why this works.
The problem could be a combination of things, a bug in both the old Mono runtime and how the debugger-libs think things should be handled. The old runtime is not going to be supported on Unity as it has been labled legacy and will therefore not be patched further.

**Comment by fjqingyou** [comment]
@miniwolf 

my english versy bad, you read this text body, probably very difficulty, because a great many english word from web translate,  forgive please , thanks!

I have an idea, Do you see if it is feasible

I've tried it. if property get or set have code body,for example

private int m_TestProperty;
private int TestProperty{
     get{
         return m_TestProperty;
    }
     set{
          m_TestProperty = value;
     }
}

if break point set on code " return m_TestProperty;" or " m_TestProperty = value;", debug runing mode or step out mode, execute to these ones here break point code, debugger will been break down right.

so, can you on step in event, judge current context, analysis step in target is property read or write ? such as c# reflection?

if feasible, can you auto add and remove a temporary execute break point on property get or set frist line code,  and temporary togger to step out mode , so,  this runing behavior, similar step in. and break down sucess.

if don't have property body, so step in behavior not significance, and because step in hang , so direct temporary togger to step out mode too.

i think this programme feasible.

but, exists a question, read one or many property value use to call method  parameter, temporary togger step in mode to step out mode, can it be normal?

**Comment by fjqingyou** [comment]
hmm,  only environmental not normal step in?

**Comment by miniwolf** [comment]
I don't know if this is feasible. I would rather try to make sure that the underlying library is working correctly. I will move this issue forward with the people responsible at mono. Then I will return when I know more about this.
However to other's how might have the same issue, this is currently unsupported on the old .NET 3.5 runtime, using .NET 4.6 works.

**Comment by miniwolf** [comment]
I have confirmed that the problems lies within the debugger-libs, I have filed a bug report with Microsoft to get this issue fixed.

**Comment by fjqingyou** [comment]
@miniwolf 

company using this version, If can, do not want to update in the short term.

Since this question is Mono, then I close this issues!

Thank you for your help!

**Comment by fjqingyou** [comment]
@miniwolf 

hmm, i have a new problem, i'm using F5 debug startup, often cause Unity No response.

Stop Debug , Unity Return to normal.

but, Not every time. 

I don't know what circumstances will trigger this problem.

I wonder if it's the problem of Mono, too. or VSCode?

**Comment by fjqingyou** [comment]
The probability of this situation appears, about 5% to 10%, and i need create a new Issues?

**Comment by miniwolf** [comment]
I have heard about this before: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/#post-3472263
I have yet to figure this out. Also figuring out under what circumstances it happens.

**Comment by fjqingyou** [comment]
I hope it is because it is just reading or writing property, that is, the current bug. Ha-ha！

After all, this is also a debugger hang!

thanks!  good bye!
